#!/usr/bin/env python3
"""Fetch the speaker line-up from Indico and append it into src/content/lineup.yaml.

Replaces the old build-time live fetch: run this whenever the Indico programme
changes, commit the resulting YAML, and the site reads it as static content.

    python3 scripts/fetch_speakers.py            # append/refresh lineup.yaml
    python3 scripts/fetch_speakers.py --selftest # offline sanity check, no network

Append, not clobber: existing entries are kept and merged by name. A speaker who
returns across years accumulates editions in a list (`edition: [...]`), and
hand-set fields (`featured: true`, `photo`) survive regeneration. Indico-derived
fields (affiliation, track) refresh from the latest fetch.

Editions and their Indico ids come from src/content/event.yaml (indicoId per
edition). Only editions with an indicoId are fetched. Stdlib only.
"""
import json
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EVENT_YAML = ROOT / "src" / "content" / "event.yaml"
OUT_YAML = ROOT / "src" / "content" / "lineup.yaml"
INDICO = "https://events.canonical.com/export/event/{id}.json?detail=contributions"


def read_editions(path: Path) -> dict[str, int]:
    """Map edition slug -> indicoId by scanning event.yaml.

    ponytail: targeted line scan, not a full YAML parse, to stay dependency-free.
    Relies on event.yaml's shape: top-level `slug:` at column 0, `indicoId: N`
    indented under it. If that layout changes, switch to PyYAML.
    """
    editions: dict[str, int] = {}
    slug: str | None = None
    for line in path.read_text(encoding="utf-8").splitlines():
        top = re.match(r"^([A-Za-z0-9_-]+):\s*$", line)
        if top:
            slug = top.group(1)
            continue
        got = re.match(r"^\s+indicoId:\s*(\d+)", line)
        if got and slug:
            editions[slug] = int(got.group(1))
    return editions


def speaker_name(s: dict) -> str:
    full = " ".join(filter(None, [s.get("first_name"), s.get("last_name")])).strip()
    return full or (s.get("fullName") or "").strip()


def fetch(event_id: int) -> list[dict]:
    url = INDICO.format(id=event_id)
    with urllib.request.urlopen(url, timeout=30) as resp:
        data = json.load(resp)
    return data.get("results", [{}])[0].get("contributions", []) or []


def speakers_for(event_id: int) -> list[dict]:
    """Dedup speakers across an edition's contributions (mirrors src/lib/indico.ts)."""
    by_key: dict[str, dict] = {}
    for c in fetch(event_id):
        track = c.get("track") or None
        for s in c.get("speakers") or []:
            name = speaker_name(s)
            if not name:
                continue
            key = str(s.get("person_id") or s.get("id") or name)
            if key not in by_key:
                by_key[key] = {
                    "name": name,
                    "affiliation": (s.get("affiliation") or "").strip() or None,
                    "track": track,
                }
    return sorted(by_key.values(), key=lambda x: x["name"].lower())


def slugify(s: str) -> str:
    return re.sub(r"-+", "-", re.sub(r"[^a-z0-9]+", "-", s.lower())).strip("-")


def dump_yaml(entries: list[dict]) -> str:
    """Emit a YAML list. Values go through json.dumps -> always-valid YAML.

    `edition` is a flow list (a JSON array is valid YAML). Each item gets a
    unique `id` (slugified name); Astro's file loader requires one for
    list-shaped collections. `featured: true` is emitted only when set.
    """
    q = lambda v: json.dumps(v, ensure_ascii=False)  # noqa: E731
    lines = [
        "# Generated by scripts/fetch_speakers.py from Indico. Regenerate to append",
        "# new speakers; a hand-set `featured: true` survives regeneration.",
        "# Regenerate: python3 scripts/fetch_speakers.py",
        "",
    ]
    seen: dict[str, int] = {}
    for e in entries:
        base = slugify(e["name"])
        seen[base] = seen.get(base, 0) + 1
        eid = base if seen[base] == 1 else f"{base}-{seen[base]}"
        lines.append(f"- id: {q(eid)}")
        lines.append(f"  edition: {q(sorted(set(e['edition'])))}")
        lines.append(f"  name: {q(e['name'])}")
        if e.get("affiliation"):
            lines.append(f"  affiliation: {q(e['affiliation'])}")
        if e.get("track"):
            lines.append(f"  track: {q(e['track'])}")
        if e.get("featured"):
            lines.append("  featured: true")
        if e.get("photo"):
            lines.append(f"  photo: {q(e['photo'])}")
    return "\n".join(lines) + "\n"


def load_yaml(path: Path) -> list[dict]:
    """Parse a lineup.yaml we previously wrote, so a rerun can append to it.

    Understands only this file's shape: `- id: <json>` items followed by indented
    `key: <json>` scalars. Tolerates the older string-`edition` format by
    normalising it to a list. ponytail: bespoke parser, not PyYAML, to stay
    dependency-free; it only has to read what dump_yaml writes.
    """
    if not path.exists():
        return []
    entries: list[dict] = []
    cur: dict | None = None
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("- id:"):
            cur = {}
            entries.append(cur)
            continue
        m = re.match(r"^\s+(\w+):\s*(.+)$", line)
        if not (m and cur is not None):
            continue
        key, raw = m.group(1), m.group(2)
        try:
            cur[key] = json.loads(raw)
        except json.JSONDecodeError:
            cur[key] = raw
    for e in entries:
        ed = e.get("edition")
        e["edition"] = [ed] if isinstance(ed, str) else (ed if isinstance(ed, list) else [])
    return [e for e in entries if e.get("name")]


def selftest() -> None:
    # event.yaml scan
    import tempfile

    sample = "india-2026:\n  name: X\n  indicoId: 157\nindia-2025:\n  indicoId: 136\n"
    with tempfile.NamedTemporaryFile("w", suffix=".yaml", delete=False) as f:
        f.write(sample)
        tmp = Path(f.name)
    assert read_editions(tmp) == {"india-2026": 157, "india-2025": 136}
    tmp.unlink()
    # name join + fallback
    assert speaker_name({"first_name": "Ada", "last_name": "Lovelace"}) == "Ada Lovelace"
    assert speaker_name({"fullName": "Grace Hopper"}) == "Grace Hopper"
    assert speaker_name({}) == ""
    assert slugify("Abdul Hakkeem P A") == "abdul-hakkeem-p-a"
    # yaml escaping + edition list + featured flag
    out = dump_yaml([{"edition": ["india-2026"], "name": 'A: "B"', "track": "AI/ML", "affiliation": None, "featured": True}])
    assert '  name: "A: \\"B\\""' in out
    assert '  edition: ["india-2026"]' in out
    assert "  featured: true" in out
    assert "- id:" in out  # file loader needs an id per item
    assert "affiliation" not in out  # None dropped
    # duplicate names get suffixed ids (name-only now, not edition-prefixed)
    dup = dump_yaml([{"edition": ["x"], "name": "Jo"}, {"edition": ["x"], "name": "Jo"}])
    assert '- id: "jo"' in dup and '- id: "jo-2"' in dup
    # round-trip: dump -> load preserves featured + the edition list
    with tempfile.NamedTemporaryFile("w", suffix=".yaml", delete=False) as f:
        f.write(dump_yaml([{"edition": ["india-2025", "india-2026"], "name": "Jo", "featured": True}]))
        rt = Path(f.name)
    assert load_yaml(rt) == [{"edition": ["india-2025", "india-2026"], "name": "Jo", "featured": True}]
    rt.unlink()
    # old string-edition format normalises to a list on load
    with tempfile.NamedTemporaryFile("w", suffix=".yaml", delete=False) as f:
        f.write('- id: "jo"\n  edition: "india-2025"\n  name: "Jo"\n')
        old = Path(f.name)
    assert load_yaml(old) == [{"edition": ["india-2025"], "name": "Jo"}]
    old.unlink()
    print("selftest ok")


def main() -> int:
    if "--selftest" in sys.argv:
        selftest()
        return 0

    editions = read_editions(EVENT_YAML)
    editions = {slug: eid for slug, eid in editions.items() if eid}
    if not editions:
        print("No editions with an indicoId in event.yaml; nothing to do.", file=sys.stderr)
        return 1

    # Append into what's already there, merging by name.
    by_name: dict[str, dict] = {slugify(e["name"]): e for e in load_yaml(OUT_YAML)}
    had = len(by_name)

    failures = 0
    for slug, eid in editions.items():
        try:
            people = speakers_for(eid)
        except Exception as err:  # noqa: BLE001
            print(f"[warn] {slug} (event {eid}): {err}", file=sys.stderr)
            failures += 1
            continue
        for p in people:
            ent = by_name.get(slugify(p["name"]))
            if ent is None:
                by_name[slugify(p["name"])] = {"name": p["name"], "edition": [slug], **{k: p[k] for k in ("affiliation", "track") if p.get(k)}}
                continue
            if slug not in ent["edition"]:
                ent["edition"].append(slug)
            # Refresh Indico-derived fields; leave the manual `featured` flag be.
            for k in ("affiliation", "track"):
                if p.get(k):
                    ent[k] = p[k]
        print(f"{slug}: {len(people)} speakers")

    # Nothing to write and nothing to keep - don't touch the file.
    if not by_name and failures:
        print("All fetches failed and no existing line-up; leaving lineup.yaml untouched.", file=sys.stderr)
        return 1

    entries = sorted(by_name.values(), key=lambda x: x["name"].lower())
    OUT_YAML.write_text(dump_yaml(entries), encoding="utf-8")
    print(f"Wrote {len(entries)} speakers ({len(by_name) - had} new) to {OUT_YAML.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
